//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public int WorkID { get; set; }
        public int OrderID { get; set; }
        public int EmployeeID { get; set; }
        public int ServiceID { get; set; }
        public int PartID { get; set; }
        public int InventoryID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual Parts Parts { get; set; }
        public virtual Services Services { get; set; }
    }
}
